import doctor1 from '../../assets/img/doctorImg/doctor1.jpg';
import doctor2 from '../../assets/img/doctorImg/doctor2.jpg';
import doctor3 from '../../assets/img/doctorImg/doctor3.jpg';


export const doctorInfo = [
  {
    id: 1,
    image: doctor1,
    name: "Doctor's Name",
    specialist: 'Neurology',
    linkinLink: '',
    fbLink: '',
    instaLink: '',
  },
  {
    id: 2,
    image: doctor2,
    name: "Doctor's Name",
    specialist: 'Neurology',
    linkedinLink: '',
    fbLink: '',
    instaLink: '',
  },
  {
    id: 3,
    image: doctor3,
    name: "Doctor's Name",
    specialist: 'Neurology',
    linkinLink: '',
    fbLink: '',
    instaLink: '',
  },
  {
    id: 4,
    image: doctor1,
    name: "Doctor's Name",
    specialist: 'Neurology',
    linkinLink: '',
    fbLink: '',
    instaLink: '',
  },
  {
    id: 5,
    image: doctor2,
    name: "Doctor's Name",
    specialist: 'Neurology',
    linkinLink: '',
    fbLink: '',
    instaLink: '',
  },
  {
    id: 6,
    image: doctor3,
    name: "Doctor's Name",
    specialist: 'Neurology',
    linkinLink: '',
    fbLink: '',
    instaLink: '',
  },
  {
    id: 7,
    image: doctor1,
    name: "Doctor's Name",
    specialist: 'Neurology',
    linkinLink: '',
    fbLink: '',
    instaLink: '',
  },
  {
    id: 8,
    image: doctor2,
    name: "Doctor's Name",
    specialist: 'Neurology',
    linkinLink: '',
    fbLink: '',
    instaLink: '',
  },
  {
    id: 9,
    image: doctor3,
    name: "Doctor's Name",
    specialist: 'Neurology',
    linkinLink: '',
    fbLink: '',
    instaLink: '',
  },
];