export const doctorInfo = [
  {
    id: 1,
    image: '../src/assets/img/doctorImg/doctor1.jpg',
    name: "Doctor's Name",
    specialist: 'Neurology',
    linkinLink: '',
    fbLink: '',
    instaLink: '',
  },
  {
    id: 2,
    image: '../src/assets/img/doctorImg/doctor2.jpg',
    name: "Doctor's Name",
    specialist: 'Neurology',
    linkedinLink: '',
    fbLink: '',
    instaLink: '',
  },
  {
    id: 3,
    image: '../src/assets/img/doctorImg/doctor3.jpg',
    name: "Doctor's Name",
    specialist: 'Neurology',
    linkinLink: '',
    fbLink: '',
    instaLink: '',
  },
  {
    id: 4,
    image: '../src/assets/img/doctorImg/doctor1.jpg',
    name: "Doctor's Name",
    specialist: 'Neurology',
    linkinLink: '',
    fbLink: '',
    instaLink: '',
  },
  {
    id: 5,
    image: '../src/assets/img/doctorImg/doctor2.jpg',
    name: "Doctor's Name",
    specialist: 'Neurology',
    linkinLink: '',
    fbLink: '',
    instaLink: '',
  },
  {
    id: 6,
    image: '../src/assets/img/doctorImg/doctor3.jpg',
    name: "Doctor's Name",
    specialist: 'Neurology',
    linkinLink: '',
    fbLink: '',
    instaLink: '',
  },
  {
    id: 7,
    image: '../src/assets/img/doctorImg/doctor1.jpg',
    name: "Doctor's Name",
    specialist: 'Neurology',
    linkinLink: '',
    fbLink: '',
    instaLink: '',
  },
  {
    id: 8,
    image: '../src/assets/img/doctorImg/doctor2.jpg',
    name: "Doctor's Name",
    specialist: 'Neurology',
    linkinLink: '',
    fbLink: '',
    instaLink: '',
  },
  {
    id: 9,
    image: '../src/assets/img/doctorImg/doctor3.jpg',
    name: "Doctor's Name",
    specialist: 'Neurology',
    linkinLink: '',
    fbLink: '',
    instaLink: '',
  },
];