export { default as CalendarSvg } from './calendar.svg'
export { default as CashSvg } from './cash.svg'
export { default as featured1 } from './featured-1.jpg'
export { default as featured2 } from './featured-2.jpg'
export { default as ImgLine } from './img-line.svg'
export { default as TeamSvg } from './team.svg'
export { default as WelcomeDoc } from './welcome-doctors.jpg'
