export { default as CalendarSvg } from './calendar.svg'
export { default as CashSvg } from './cash.svg'
export { default as HeartIcon } from './home-heart-icon.svg'
export { default as ImgLine } from './img-line.svg'
export { default as TeamSvg } from './team.svg'
export { default as WelcomeDoc } from './welcome-doctors.jpg'