const patientsData = [
  {
    patientID: '#P-00001',
    patientName: 'Gary Moore',
    gender: 'Male',
    age: 80,
    dBirth: '1943-01-30',
    address: 'address 1',
    phoneNumber: '09452365718',
    disease: 'Happy',
    dDoctor: 'Dr. Wonder Happ',
    patientStatus: 'pending',
  },
  {
    patientID: '#P-00002',
    patientName: 'Alexandra Cooper',
    gender: 'Female',
    age: 40,
    dBirth: '1983-12-35',
    address: 'address 2',
    phoneNumber: '0919536248',
    disease: 'Taking Nap',
    dDoctor: 'Dr. Rich Reach',
    patientStatus: 'pending',
  },
  {
    patientID: '#P-00003',
    patientName: 'Dexter Ellis',
    gender: 'Male',
    age: 35,
    dBirth: '1988-02-20',
    address: 'address 3',
    phoneNumber: '09206535984',
    disease: 'Hello',
    dDoctor: 'Dr. Rich Reach',
    patientStatus: 'approved',
  },
  {
    patientID: '#P-00004',
    patientName: 'John Holland',
    gender: 'Male',
    age: 50,
    dBirth: '1973-05-18',
    address: 'address 4',
    phoneNumber: '09552365784',
    disease: 'Chilling',
    dDoctor: 'Dr. Alejandro Salceda',
    patientStatus: 'approved',
  },
  {
    patientID: '#P-00005',
    patientName: 'Kaye Maya',
    gender: 'Female',
    age: 45,
    dBirth: '1978-11-01',
    address: 'address 5',
    phoneNumber: '09195685422',
    disease: 'Heart Burn',
    dDoctor: 'Dr. Becca Haper',
    patientStatus: 'approved',
  },
]

export default patientsData
