/* const doctorsData = [
  {
    doctorID: '#D-00001',
    doctorName: 'Dr. Samantha Smith',
    gender: 'Female',
    specialization: 'Cardiology',
    dateOfBirth: '1975-05-15',
    address: '123 Medical Street, Cityville',
    phoneNumber: '0987654321',
    email: 'dr.samantha@example.com',
    hospitalAffiliation: 'City General Hospital',
    isAvailable: true,
    shiftTiming: '9:00 AM - 5:00 PM',
    patients: [
      {
        patientID: '#P-00001',
        patientName: 'Gary Moore',
        gender: 'Male',
        age: 80,
        dateOfBirth: '1943-01-30',
        address: 'Address 1',
        phoneNumber: '09452365718',
        disease: 'Happy',
        dDoctor: 'Dr. Samantha Smith',
        patientStatus: 'pending',
      },
      {
        patientID: '#P-00002',
        patientName: 'Alexandra Cooper',
        gender: 'Female',
        age: 40,
        dBirth: '1983-12-35',
        address: 'address 2',
        phoneNumber: '0919536248',
        disease: 'Taking Nap',
        dDoctor: 'Dr. Samantha Smith',
        patientStatus: 'pending',
      },
    ],
  },
  {
    doctorID: '#D-00002',
    doctorName: 'Dr. Michael Johnson',
    gender: 'Male',
    specialization: 'Orthopedics',
    dateOfBirth: '1980-08-20',
    address: '456 Bone Street, Healthtown',
    phoneNumber: '0123456789',
    email: 'dr.michael@example.com',
    hospitalAffiliation: 'Healthcare Clinic',
    isAvailable: true,
    shiftTiming: '10:00 AM - 6:00 PM',
    patients: [
      {
        patientID: '#P-00003',
        patientName: 'Dexter Ellis',
        gender: 'Male',
        age: 35,
        dBirth: '1988-02-20',
        address: 'address 3',
        phoneNumber: '09206535984',
        disease: 'Hello',
        dDoctor: 'Dr. Michael Johnson',
        patientStatus: 'approved',
      },
    ],
  },
  {
    doctorID: '#D-00003',
    doctorName: 'Dr. Emily Davis',
    gender: 'Female',
    specialization: 'Pediatrics',
    dateOfBirth: '1978-03-12',
    address: '789 Child Avenue, Kidsville',
    phoneNumber: '0765432109',
    email: 'dr.emily@example.com',
    hospitalAffiliation: "Children's Hospital",
    isAvailable: false,
    shiftTiming: 'Not available',
    patients: [
      {
        patientID: '#P-00004',
        patientName: 'John Holland',
        gender: 'Male',
        age: 50,
        dBirth: '1973-05-18',
        address: 'address 4',
        phoneNumber: '09552365784',
        disease: 'Chilling',
        dDoctor: 'Dr. Emily Davis',
        patientStatus: 'approved',
      },
      {
        patientID: '#P-00005',
        patientName: 'Kaye Maya',
        gender: 'Female',
        age: 45,
        dBirth: '1978-11-01',
        address: 'address 5',
        phoneNumber: '09195685422',
        disease: 'Heart Burn',
        dDoctor: 'Dr. Emily Davis',
        patientStatus: 'approved',
      },
    ],
  },
  {
    doctorID: '#D-00004',
    doctorName: 'Dr. John Anderson',
    gender: 'Male',
    specialization: 'Dermatology',
    dateOfBirth: '1985-11-25',
    address: '101 Skin Lane, Dermatown',
    phoneNumber: '0932145678',
    email: 'dr.john@example.com',
    hospitalAffiliation: 'SkinCare Hospital',
    isAvailable: true,
    shiftTiming: '8:00 AM - 4:00 PM',
    patients: [
      {
        patientID: '#P-00006',
        patientName: 'Alice Johnson',
        gender: 'Female',
        age: 35,
        dateOfBirth: '1989-04-22',
        address: '456 Health Street, Wellnessville',
        phoneNumber: '0987654321',
        disease: 'Common Cold',
        dDoctor: 'Dr. John Anderson',
        patientStatus: 'pending',
      },
      {
        patientID: '#P-00007',
        patientName: 'Bob Miller',
        gender: 'Male',
        age: 45,
        dateOfBirth: '1979-12-15',
        address: '789 Care Avenue, Healthtown',
        phoneNumber: '0123456789',
        disease: 'Hypertension',
        dDoctor: 'Dr. John Anderson',
        patientStatus: 'completed',
      },
    ],
  },
  {
    doctorID: '#D-00005',
    doctorName: 'Dr. Lisa Miller',
    gender: 'Female',
    specialization: 'Internal Medicine',
    dateOfBirth: '1982-07-07',
    address: '202 Wellness Street, Healthville',
    phoneNumber: '0876543210',
    email: 'dr.lisa@example.com',
    hospitalAffiliation: 'Health Wellness Center',
    isAvailable: true,
    shiftTiming: '11:00 AM - 7:00 PM',
    patients: [
      {
        patientID: '#P-00008',
        patientName: 'Catherine Davis',
        gender: 'Female',
        age: 28,
        dateOfBirth: '1996-08-05',
        address: '101 Healing Lane, Curetown',
        phoneNumber: '0765432109',
        disease: 'Allergies',
        dDoctor: 'Dr. Lisa Miller',
        patientStatus: 'pending',
      },
      {
        patientID: '#P-00009',
        patientName: 'David Anderson',
        gender: 'Male',
        age: 50,
        dateOfBirth: '1972-03-30',
        address: '202 Recovery Street, Healville',
        phoneNumber: '0932145678',
        disease: 'Diabetes',
        dDoctor: 'Dr. Lisa Miller',
        patientStatus: 'completed',
      },
      {
        patientID: '#P-00010',
        patientName: 'Eva Smith',
        gender: 'Female',
        age: 22,
        dateOfBirth: '2000-11-10',
        address: '303 Cure Lane, Healthville',
        phoneNumber: '0876543210',
        disease: 'Flu',
        dDoctor: 'Dr. Lisa Miller',
        patientStatus: 'pending',
      },
    ],
  },
]

export default doctorsData */

const doctorsData = [
  {
    doctorID: '#D-00001',
    doctorName: 'Dr. Samantha Smith',
    gender: 'Female',
    specialization: 'Cardiology',
    dateOfBirth: '1975-05-15',
    address: '123 Medical Street, Cityville',
    phoneNumber: '0987654321',
    email: 'dr.samantha@example.com',
    hospitalAffiliation: 'City General Hospital',
    isAvailable: true,
    shiftTiming: '9:00 AM - 5:00 PM',
    patients: 2
  },
  {
    doctorID: '#D-00002',
    doctorName: 'Dr. Michael Johnson',
    gender: 'Male',
    specialization: 'Orthopedics',
    dateOfBirth: '1980-08-20',
    address: '456 Bone Street, Healthtown',
    phoneNumber: '0123456789',
    email: 'dr.michael@example.com',
    hospitalAffiliation: 'Healthcare Clinic',
    isAvailable: true,
    shiftTiming: '10:00 AM - 6:00 PM',
    patients: 1
  },
  {
    doctorID: '#D-00003',
    doctorName: 'Dr. Emily Davis',
    gender: 'Female',
    specialization: 'Pediatrics',
    dateOfBirth: '1978-03-12',
    address: '789 Child Avenue, Kidsville',
    phoneNumber: '0765432109',
    email: 'dr.emily@example.com',
    hospitalAffiliation: "Children's Hospital",
    isAvailable: false,
    shiftTiming: 'Not available',
    patients: 2
  },
  {
    doctorID: '#D-00004',
    doctorName: 'Dr. John Anderson',
    gender: 'Male',
    specialization: 'Dermatology',
    dateOfBirth: '1985-11-25',
    address: '101 Skin Lane, Dermatown',
    phoneNumber: '0932145678',
    email: 'dr.john@example.com',
    hospitalAffiliation: 'SkinCare Hospital',
    isAvailable: true,
    shiftTiming: '8:00 AM - 4:00 PM',
    patients: 3
  },
  {
    doctorID: '#D-00005',
    doctorName: 'Dr. Lisa Miller',
    gender: 'Female',
    specialization: 'Internal Medicine',
    dateOfBirth: '1982-07-07',
    address: '202 Wellness Street, Healthville',
    phoneNumber: '0876543210',
    email: 'dr.lisa@example.com',
    hospitalAffiliation: 'Health Wellness Center',
    isAvailable: true,
    shiftTiming: '11:00 AM - 7:00 PM',
    patients: 2
  },
]

export default doctorsData